# Generated by Django 3.0.4 on 2020-06-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eventstream', '0003_auto_20200616_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='read_date',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
